services:
  Wangaz\ContaoIsotopeWirecardBundle\EventListener\RequestListener:
    arguments:
      - '@database_connection'
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 31 }
